namespace GBoy.Core;
public partial class Cpu
{
    public struct Opcode
    {
        public string Name;
        public string Oper;
        public string Format;
        public byte Size;
             
        public Opcode(string name, string oper, string format, byte size)
        {
            Name = name;
            Oper = oper;
            Format = format;
            Size = size;
        }
    }
    
	public List<Opcode> opInfo00;
	public List<Opcode> opInfoCB;

	public void GenerateOpInfo()
	{
		opInfo00 = new();
		opInfoCB = new();

		opInfo00.Add(new Opcode("nop", "n/a", "", 1)); //00
		opInfo00.Add(new Opcode("ld", "bc,", "x4", 3)); //01
		opInfo00.Add(new Opcode("ld", "(bc),a", "", 1)); //02
		opInfo00.Add(new Opcode("inc", "bc", "", 1)); //03
		opInfo00.Add(new Opcode("inc", "b", "", 1)); //04
		opInfo00.Add(new Opcode("dec", "b", "", 1)); //05
		opInfo00.Add(new Opcode("ld", "b,", "x2", 2)); //06
		opInfo00.Add(new Opcode("rlca", "n/a", "", 1)); //07
		opInfo00.Add(new Opcode("ld", "sp", "x4", 3)); //08
		opInfo00.Add(new Opcode("add", "hl,bc", "", 1)); //09
		opInfo00.Add(new Opcode("ld", "a,(bc)", "", 1)); //0A
		opInfo00.Add(new Opcode("dec", "bc", "", 1)); //0B
		opInfo00.Add(new Opcode("inc", "c", "", 1)); //0C
		opInfo00.Add(new Opcode("dec", "c", "", 1)); //0D
		opInfo00.Add(new Opcode("ld", "c,", "x2", 2)); //0E
		opInfo00.Add(new Opcode("rrca", "n/a", "", 1)); //0F
		opInfo00.Add(new Opcode("stop", "0", "", 2)); //10
		opInfo00.Add(new Opcode("ld", "de,", "x4", 3)); //11
		opInfo00.Add(new Opcode("ld", "(de),a", "", 1)); //12
		opInfo00.Add(new Opcode("inc", "de", "", 1)); //13
		opInfo00.Add(new Opcode("inc", "d", "", 1)); //14
		opInfo00.Add(new Opcode("dec", "d", "", 1)); //15
		opInfo00.Add(new Opcode("ld", "d,", "x2", 2)); //16
		opInfo00.Add(new Opcode("rla", "n/a", "", 1)); //17
		opInfo00.Add(new Opcode("jr", "", "x4", 2)); //18
		opInfo00.Add(new Opcode("add", "hl,de", "", 1)); //19
		opInfo00.Add(new Opcode("ld", "a,(de)", "", 1)); //1A
		opInfo00.Add(new Opcode("dec", "de", "", 1)); //1B
		opInfo00.Add(new Opcode("inc", "e", "", 1)); //1C
		opInfo00.Add(new Opcode("dec", "e", "", 1)); //1D
		opInfo00.Add(new Opcode("ld", "e,", "x2", 2)); //1E
		opInfo00.Add(new Opcode("rra", "n/a", "", 1)); //1F
		opInfo00.Add(new Opcode("jr", "nz,", "x4", 2)); //20
		opInfo00.Add(new Opcode("ld", "hl,", "x4", 3)); //21
		opInfo00.Add(new Opcode("ld", "(hl+),a", "", 1)); //22
		opInfo00.Add(new Opcode("inc", "hl", "", 1)); //23
		opInfo00.Add(new Opcode("inc", "h", "", 1)); //24
		opInfo00.Add(new Opcode("dec", "h", "", 1)); //25
		opInfo00.Add(new Opcode("ld", "h,", "x2", 2)); //26
		opInfo00.Add(new Opcode("daa", "n/a", "", 1)); //27
		opInfo00.Add(new Opcode("jr", "z,", "x4", 2)); //28
		opInfo00.Add(new Opcode("add", "hl,hl", "", 1)); //29
		opInfo00.Add(new Opcode("ld", "a,(hl+)", "", 1)); //2A
		opInfo00.Add(new Opcode("dec", "hl", "", 1)); //2B
		opInfo00.Add(new Opcode("inc", "l", "", 1)); //2C
		opInfo00.Add(new Opcode("dec", "l", "", 1)); //2D
		opInfo00.Add(new Opcode("ld", "l,", "x2", 2)); //2E
		opInfo00.Add(new Opcode("cpl", "n/a", "", 1)); //2F
		opInfo00.Add(new Opcode("jr", "nc,", "x4", 2)); //30
		opInfo00.Add(new Opcode("ld", "sp,", "x4", 3)); //31
		opInfo00.Add(new Opcode("ld", "(hl-),a", "", 1)); //32
		opInfo00.Add(new Opcode("inc", "sp", "", 1)); //33
		opInfo00.Add(new Opcode("inc", "(hl)", "", 1)); //34
		opInfo00.Add(new Opcode("dec", "(hl)", "", 1)); //35
		opInfo00.Add(new Opcode("ld", "(hl),", "x2", 2)); //36
		opInfo00.Add(new Opcode("scf", "n/a", "", 1)); //37
		opInfo00.Add(new Opcode("jr", "c,", "x4", 2)); //38
		opInfo00.Add(new Opcode("add", "hl,sp", "", 1)); //39
		opInfo00.Add(new Opcode("ld", "a,(hl-)", "", 1)); //3A
		opInfo00.Add(new Opcode("dec", "sp", "", 1)); //3B
		opInfo00.Add(new Opcode("inc", "a", "", 1)); //3C
		opInfo00.Add(new Opcode("dec", "a", "", 1)); //3D
		opInfo00.Add(new Opcode("ld", "a,", "x2", 2)); //3E
		opInfo00.Add(new Opcode("ccf", "n/a", "", 1)); //3F
		opInfo00.Add(new Opcode("ld", "b,b", "", 1)); //40
		opInfo00.Add(new Opcode("ld", "b,c", "", 1)); //41
		opInfo00.Add(new Opcode("ld", "b,d", "", 1)); //42
		opInfo00.Add(new Opcode("ld", "b,e", "", 1)); //43
		opInfo00.Add(new Opcode("ld", "b,h", "", 1)); //44
		opInfo00.Add(new Opcode("ld", "b,l", "", 1)); //45
		opInfo00.Add(new Opcode("ld", "b,(hl)", "", 1)); //46
		opInfo00.Add(new Opcode("ld", "b,a", "", 1)); //47
		opInfo00.Add(new Opcode("ld", "c,b", "", 1)); //48
		opInfo00.Add(new Opcode("ld", "c,c", "", 1)); //49
		opInfo00.Add(new Opcode("ld", "c,d", "", 1)); //4A
		opInfo00.Add(new Opcode("ld", "c,e", "", 1)); //4B
		opInfo00.Add(new Opcode("ld", "c,h", "", 1)); //4C
		opInfo00.Add(new Opcode("ld", "c,l", "", 1)); //4D
		opInfo00.Add(new Opcode("ld", "c,(hl)", "", 1)); //4E
		opInfo00.Add(new Opcode("ld", "c,a", "", 1)); //4F
		opInfo00.Add(new Opcode("ld", "d,b", "", 1)); //50
		opInfo00.Add(new Opcode("ld", "d,c", "", 1)); //51
		opInfo00.Add(new Opcode("ld", "d,d", "", 1)); //52
		opInfo00.Add(new Opcode("ld", "d,e", "", 1)); //53
		opInfo00.Add(new Opcode("ld", "d,h", "", 1)); //54
		opInfo00.Add(new Opcode("ld", "d,l", "", 1)); //55
		opInfo00.Add(new Opcode("ld", "d,(hl)", "", 1)); //56
		opInfo00.Add(new Opcode("ld", "d,a", "", 1)); //57
		opInfo00.Add(new Opcode("ld", "e,b", "", 1)); //58
		opInfo00.Add(new Opcode("ld", "e,c", "", 1)); //59
		opInfo00.Add(new Opcode("ld", "e,d", "", 1)); //5A
		opInfo00.Add(new Opcode("ld", "e,e", "", 1)); //5B
		opInfo00.Add(new Opcode("ld", "e,h", "", 1)); //5C
		opInfo00.Add(new Opcode("ld", "e,l", "", 1)); //5D
		opInfo00.Add(new Opcode("ld", "e,(hl)", "", 1)); //5E
		opInfo00.Add(new Opcode("ld", "e,a", "", 1)); //5F
		opInfo00.Add(new Opcode("ld", "h,b", "", 1)); //60
		opInfo00.Add(new Opcode("ld", "h,c", "", 1)); //61
		opInfo00.Add(new Opcode("ld", "h,d", "", 1)); //62
		opInfo00.Add(new Opcode("ld", "h,e", "", 1)); //63
		opInfo00.Add(new Opcode("ld", "h,h", "", 1)); //64
		opInfo00.Add(new Opcode("ld", "h,l", "", 1)); //65
		opInfo00.Add(new Opcode("ld", "h,(hl)", "", 1)); //66
		opInfo00.Add(new Opcode("ld", "h,a", "", 1)); //67
		opInfo00.Add(new Opcode("ld", "l,b", "", 1)); //68
		opInfo00.Add(new Opcode("ld", "l,c", "", 1)); //69
		opInfo00.Add(new Opcode("ld", "l,d", "", 1)); //6A
		opInfo00.Add(new Opcode("ld", "l,e", "", 1)); //6B
		opInfo00.Add(new Opcode("ld", "l,h", "", 1)); //6C
		opInfo00.Add(new Opcode("ld", "l,l", "", 1)); //6D
		opInfo00.Add(new Opcode("ld", "l,(hl)", "", 1)); //6E
		opInfo00.Add(new Opcode("ld", "l,a", "", 1)); //6F
		opInfo00.Add(new Opcode("ld", "(hl),b", "", 1)); //70
		opInfo00.Add(new Opcode("ld", "(hl),c", "", 1)); //71
		opInfo00.Add(new Opcode("ld", "(hl),d", "", 1)); //72
		opInfo00.Add(new Opcode("ld", "(hl),e", "", 1)); //73
		opInfo00.Add(new Opcode("ld", "(hl),h", "", 1)); //74
		opInfo00.Add(new Opcode("ld", "(hl),l", "", 1)); //75
		opInfo00.Add(new Opcode("halt", "n/a", "", 1)); //76
		opInfo00.Add(new Opcode("ld", "(hl),a", "", 1)); //77
		opInfo00.Add(new Opcode("ld", "a,b", "", 1)); //78
		opInfo00.Add(new Opcode("ld", "a,c", "", 1)); //79
		opInfo00.Add(new Opcode("ld", "a,d", "", 1)); //7A
		opInfo00.Add(new Opcode("ld", "a,e", "", 1)); //7B
		opInfo00.Add(new Opcode("ld", "a,h", "", 1)); //7C
		opInfo00.Add(new Opcode("ld", "a,l", "", 1)); //7D
		opInfo00.Add(new Opcode("ld", "a,(hl)", "", 1)); //7E
		opInfo00.Add(new Opcode("ld", "a,a", "", 1)); //7F
		opInfo00.Add(new Opcode("add", "a,b", "", 1)); //80
		opInfo00.Add(new Opcode("add", "a,c", "", 1)); //81
		opInfo00.Add(new Opcode("add", "a,d", "", 1)); //82
		opInfo00.Add(new Opcode("add", "a,e", "", 1)); //83
		opInfo00.Add(new Opcode("add", "a,h", "", 1)); //84
		opInfo00.Add(new Opcode("add", "a,l", "", 1)); //85
		opInfo00.Add(new Opcode("add", "a,(hl)", "", 1)); //86
		opInfo00.Add(new Opcode("add", "a,a", "", 1)); //87
		opInfo00.Add(new Opcode("adc", "a,b", "", 1)); //88
		opInfo00.Add(new Opcode("adc", "a,c", "", 1)); //89
		opInfo00.Add(new Opcode("adc", "a,d", "", 1)); //8A
		opInfo00.Add(new Opcode("adc", "a,e", "", 1)); //8B
		opInfo00.Add(new Opcode("adc", "a,h", "", 1)); //8C
		opInfo00.Add(new Opcode("adc", "a,l", "", 1)); //8D
		opInfo00.Add(new Opcode("adc", "a,(hl)", "", 1)); //8E
		opInfo00.Add(new Opcode("adc", "a,a", "", 1)); //8F
		opInfo00.Add(new Opcode("sub", "b", "", 1)); //90
		opInfo00.Add(new Opcode("sub", "c", "", 1)); //91
		opInfo00.Add(new Opcode("sub", "d", "", 1)); //92
		opInfo00.Add(new Opcode("sub", "e", "", 1)); //93
		opInfo00.Add(new Opcode("sub", "h", "", 1)); //94
		opInfo00.Add(new Opcode("sub", "l", "", 1)); //95
		opInfo00.Add(new Opcode("sub", "(hl)", "", 1)); //96
		opInfo00.Add(new Opcode("sub", "a", "", 1)); //97
		opInfo00.Add(new Opcode("sbc", "a,b", "", 1)); //98
		opInfo00.Add(new Opcode("sbc", "a,c", "", 1)); //99
		opInfo00.Add(new Opcode("sbc", "a,d", "", 1)); //9A
		opInfo00.Add(new Opcode("sbc", "a,e", "", 1)); //9B
		opInfo00.Add(new Opcode("sbc", "a,h", "", 1)); //9C
		opInfo00.Add(new Opcode("sbc", "a,l", "", 1)); //9D
		opInfo00.Add(new Opcode("sbc", "a,(hl)", "", 1)); //9E
		opInfo00.Add(new Opcode("sbc", "a,a", "", 1)); //9F
		opInfo00.Add(new Opcode("and", "b", "", 1)); //A0
		opInfo00.Add(new Opcode("and", "c", "", 1)); //A1
		opInfo00.Add(new Opcode("and", "d", "", 1)); //A2
		opInfo00.Add(new Opcode("and", "e", "", 1)); //A3
		opInfo00.Add(new Opcode("and", "h", "", 1)); //A4
		opInfo00.Add(new Opcode("and", "l", "", 1)); //A5
		opInfo00.Add(new Opcode("and", "(hl)", "", 1)); //A6
		opInfo00.Add(new Opcode("and", "a", "", 1)); //A7
		opInfo00.Add(new Opcode("xor", "b", "", 1)); //A8
		opInfo00.Add(new Opcode("xor", "c", "", 1)); //A9
		opInfo00.Add(new Opcode("xor", "d", "", 1)); //AA
		opInfo00.Add(new Opcode("xor", "e", "", 1)); //AB
		opInfo00.Add(new Opcode("xor", "h", "", 1)); //AC
		opInfo00.Add(new Opcode("xor", "l", "", 1)); //AD
		opInfo00.Add(new Opcode("xor", "(hl)", "", 1)); //AE
		opInfo00.Add(new Opcode("xor", "a", "", 1)); //AF
		opInfo00.Add(new Opcode("or", "b", "", 1)); //B0
		opInfo00.Add(new Opcode("or", "c", "", 1)); //B1
		opInfo00.Add(new Opcode("or", "d", "", 1)); //B2
		opInfo00.Add(new Opcode("or", "e", "", 1)); //B3
		opInfo00.Add(new Opcode("or", "h", "", 1)); //B4
		opInfo00.Add(new Opcode("or", "l", "", 1)); //B5
		opInfo00.Add(new Opcode("or", "(hl)", "", 1)); //B6
		opInfo00.Add(new Opcode("or", "a", "", 1)); //B7
		opInfo00.Add(new Opcode("cp", "b", "", 1)); //B8
		opInfo00.Add(new Opcode("cp", "c", "", 1)); //B9
		opInfo00.Add(new Opcode("cp", "d", "", 1)); //BA
		opInfo00.Add(new Opcode("cp", "e", "", 1)); //BB
		opInfo00.Add(new Opcode("cp", "h", "", 1)); //BC
		opInfo00.Add(new Opcode("cp", "l", "", 1)); //BD
		opInfo00.Add(new Opcode("cp", "(hl)", "", 1)); //BE
		opInfo00.Add(new Opcode("cp", "a", "", 1)); //BF
		opInfo00.Add(new Opcode("ret", "nz", "", 1)); //C0
		opInfo00.Add(new Opcode("pop", "bc", "", 1)); //C1
		opInfo00.Add(new Opcode("jp", "", "x4", 3)); //C2
		opInfo00.Add(new Opcode("jp", "", "x4", 3)); //C3
		opInfo00.Add(new Opcode("call", "", "x4", 3)); //C4
		opInfo00.Add(new Opcode("push", "bc", "", 1)); //C5
		opInfo00.Add(new Opcode("add", "a,", "x2", 2)); //C6
		opInfo00.Add(new Opcode("rst", "00h", "", 1)); //C7
		opInfo00.Add(new Opcode("ret", "z", "", 1)); //C8
		opInfo00.Add(new Opcode("ret", "n/a", "", 1)); //C9
		opInfo00.Add(new Opcode("jp", "", "x4", 3)); //CA
		opInfo00.Add(new Opcode("prefix", "cb", "", 1)); //CB
		opInfo00.Add(new Opcode("call", "", "x4", 3)); //CC
		opInfo00.Add(new Opcode("call", "", "x4", 3)); //CD
		opInfo00.Add(new Opcode("adc", "a,", "x2", 2)); //CE
		opInfo00.Add(new Opcode("rst", "08h", "", 1)); //CF
		opInfo00.Add(new Opcode("ret", "nc", "", 1)); //D0
		opInfo00.Add(new Opcode("pop", "de", "", 1)); //D1
		opInfo00.Add(new Opcode("jp", "", "x4", 3)); //D2
		opInfo00.Add(new Opcode("pre", "", "", 0)); //D3
		opInfo00.Add(new Opcode("call", "", "x4", 3)); //D4
		opInfo00.Add(new Opcode("push", "de", "", 1)); //D5
		opInfo00.Add(new Opcode("sub", "", "x2", 2)); //D6
		opInfo00.Add(new Opcode("rst", "10h", "", 1)); //D7
		opInfo00.Add(new Opcode("ret", "c", "", 1)); //D8
		opInfo00.Add(new Opcode("reti", "n/a", "", 1)); //D9
		opInfo00.Add(new Opcode("jp", "", "x4", 3)); //DA
		opInfo00.Add(new Opcode("pre", "", "", 0)); //DB
		opInfo00.Add(new Opcode("call", "", "x4", 3)); //DC
		opInfo00.Add(new Opcode("pre", "", "", 0)); //DD
		opInfo00.Add(new Opcode("sbc", "a,", "x2", 2)); //DE
		opInfo00.Add(new Opcode("rst", "18h", "", 1)); //DF
		opInfo00.Add(new Opcode("ldh", "(a8),a", "", 2)); //E0
		opInfo00.Add(new Opcode("pop", "hl", "", 1)); //E1
		opInfo00.Add(new Opcode("ld", "(c),a", "", 2)); //E2
		opInfo00.Add(new Opcode("pre", "", "", 0)); //E3
		opInfo00.Add(new Opcode("pre", "", "", 0)); //E4
		opInfo00.Add(new Opcode("push", "hl", "", 1)); //E5
		opInfo00.Add(new Opcode("and", "", "x2", 2)); //E6
		opInfo00.Add(new Opcode("rst", "20h", "", 1)); //E7
		opInfo00.Add(new Opcode("add", "sp,", "x4", 2)); //E8
		opInfo00.Add(new Opcode("jp", "(hl)", "", 1)); //E9
		opInfo00.Add(new Opcode("ld", "a", "x4", 3)); //EA
		opInfo00.Add(new Opcode("pre", "", "", 0)); //EB
		opInfo00.Add(new Opcode("pre", "", "", 0)); //EC
		opInfo00.Add(new Opcode("pre", "", "", 0)); //ED
		opInfo00.Add(new Opcode("xor", "", "x2", 2)); //EE
		opInfo00.Add(new Opcode("rst", "28h", "", 1)); //EF
		opInfo00.Add(new Opcode("ldh", "a,(a8)", "", 2)); //F0
		opInfo00.Add(new Opcode("pop", "af", "", 1)); //F1
		opInfo00.Add(new Opcode("ld", "a,(c)", "", 2)); //F2
		opInfo00.Add(new Opcode("di", "n/a", "", 1)); //F3
		opInfo00.Add(new Opcode("pre", "", "", 0)); //F4
		opInfo00.Add(new Opcode("push", "af", "", 1)); //F5
		opInfo00.Add(new Opcode("or", "", "x2", 2)); //F6
		opInfo00.Add(new Opcode("rst", "30h", "", 1)); //F7
		opInfo00.Add(new Opcode("ld", "hl,sp+", "x4", 2)); //F8
		opInfo00.Add(new Opcode("ld", "sp,hl", "", 1)); //F9
		opInfo00.Add(new Opcode("ld", "()", "x4", 3)); //FA
		opInfo00.Add(new Opcode("ei", "n/a", "", 1)); //FB
		opInfo00.Add(new Opcode("pre", "", "", 0)); //FC
		opInfo00.Add(new Opcode("pre", "", "", 0)); //FD
		opInfo00.Add(new Opcode("cp", "", "x2", 2)); //FE
		opInfo00.Add(new Opcode("rst", "38h", "", 1)); //FF
		opInfoCB.Add(new Opcode("rlc", "b", "", 2)); //00
		opInfoCB.Add(new Opcode("rlc", "c", "", 2)); //01
		opInfoCB.Add(new Opcode("rlc", "d", "", 2)); //02
		opInfoCB.Add(new Opcode("rlc", "e", "", 2)); //03
		opInfoCB.Add(new Opcode("rlc", "h", "", 2)); //04
		opInfoCB.Add(new Opcode("rlc", "l", "", 2)); //05
		opInfoCB.Add(new Opcode("rlc", "(hl)", "", 2)); //06
		opInfoCB.Add(new Opcode("rlc", "a", "", 2)); //07
		opInfoCB.Add(new Opcode("rrc", "b", "", 2)); //08
		opInfoCB.Add(new Opcode("rrc", "c", "", 2)); //09
		opInfoCB.Add(new Opcode("rrc", "d", "", 2)); //0A
		opInfoCB.Add(new Opcode("rrc", "e", "", 2)); //0B
		opInfoCB.Add(new Opcode("rrc", "h", "", 2)); //0C
		opInfoCB.Add(new Opcode("rrc", "l", "", 2)); //0D
		opInfoCB.Add(new Opcode("rrc", "(hl)", "", 2)); //0E
		opInfoCB.Add(new Opcode("rrc", "a", "", 2)); //0F
		opInfoCB.Add(new Opcode("rl", "b", "", 2)); //10
		opInfoCB.Add(new Opcode("rl", "c", "", 2)); //11
		opInfoCB.Add(new Opcode("rl", "d", "", 2)); //12
		opInfoCB.Add(new Opcode("rl", "e", "", 2)); //13
		opInfoCB.Add(new Opcode("rl", "h", "", 2)); //14
		opInfoCB.Add(new Opcode("rl", "l", "", 2)); //15
		opInfoCB.Add(new Opcode("rl", "(hl)", "", 2)); //16
		opInfoCB.Add(new Opcode("rl", "a", "", 2)); //17
		opInfoCB.Add(new Opcode("rr", "b", "", 2)); //18
		opInfoCB.Add(new Opcode("rr", "c", "", 2)); //19
		opInfoCB.Add(new Opcode("rr", "d", "", 2)); //1A
		opInfoCB.Add(new Opcode("rr", "e", "", 2)); //1B
		opInfoCB.Add(new Opcode("rr", "h", "", 2)); //1C
		opInfoCB.Add(new Opcode("rr", "l", "", 2)); //1D
		opInfoCB.Add(new Opcode("rr", "(hl)", "", 2)); //1E
		opInfoCB.Add(new Opcode("rr", "a", "", 2)); //1F
		opInfoCB.Add(new Opcode("sla", "b", "", 2)); //20
		opInfoCB.Add(new Opcode("sla", "c", "", 2)); //21
		opInfoCB.Add(new Opcode("sla", "d", "", 2)); //22
		opInfoCB.Add(new Opcode("sla", "e", "", 2)); //23
		opInfoCB.Add(new Opcode("sla", "h", "", 2)); //24
		opInfoCB.Add(new Opcode("sla", "l", "", 2)); //25
		opInfoCB.Add(new Opcode("sla", "(hl)", "", 2)); //26
		opInfoCB.Add(new Opcode("sla", "a", "", 2)); //27
		opInfoCB.Add(new Opcode("sra", "b", "", 2)); //28
		opInfoCB.Add(new Opcode("sra", "c", "", 2)); //29
		opInfoCB.Add(new Opcode("sra", "d", "", 2)); //2A
		opInfoCB.Add(new Opcode("sra", "e", "", 2)); //2B
		opInfoCB.Add(new Opcode("sra", "h", "", 2)); //2C
		opInfoCB.Add(new Opcode("sra", "l", "", 2)); //2D
		opInfoCB.Add(new Opcode("sra", "(hl)", "", 2)); //2E
		opInfoCB.Add(new Opcode("sra", "a", "", 2)); //2F
		opInfoCB.Add(new Opcode("swap", "b", "", 2)); //30
		opInfoCB.Add(new Opcode("swap", "c", "", 2)); //31
		opInfoCB.Add(new Opcode("swap", "d", "", 2)); //32
		opInfoCB.Add(new Opcode("swap", "e", "", 2)); //33
		opInfoCB.Add(new Opcode("swap", "h", "", 2)); //34
		opInfoCB.Add(new Opcode("swap", "l", "", 2)); //35
		opInfoCB.Add(new Opcode("swap", "(hl)", "", 2)); //36
		opInfoCB.Add(new Opcode("swap", "a", "", 2)); //37
		opInfoCB.Add(new Opcode("srl", "b", "", 2)); //38
		opInfoCB.Add(new Opcode("srl", "c", "", 2)); //39
		opInfoCB.Add(new Opcode("srl", "d", "", 2)); //3A
		opInfoCB.Add(new Opcode("srl", "e", "", 2)); //3B
		opInfoCB.Add(new Opcode("srl", "h", "", 2)); //3C
		opInfoCB.Add(new Opcode("srl", "l", "", 2)); //3D
		opInfoCB.Add(new Opcode("srl", "(hl)", "", 2)); //3E
		opInfoCB.Add(new Opcode("srl", "a", "", 2)); //3F
		opInfoCB.Add(new Opcode("bit", "0,b", "", 2)); //40
		opInfoCB.Add(new Opcode("bit", "0,c", "", 2)); //41
		opInfoCB.Add(new Opcode("bit", "0,d", "", 2)); //42
		opInfoCB.Add(new Opcode("bit", "0,e", "", 2)); //43
		opInfoCB.Add(new Opcode("bit", "0,h", "", 2)); //44
		opInfoCB.Add(new Opcode("bit", "0,l", "", 2)); //45
		opInfoCB.Add(new Opcode("bit", "0,(hl)", "", 2)); //46
		opInfoCB.Add(new Opcode("bit", "0,a", "", 2)); //47
		opInfoCB.Add(new Opcode("bit", "1,b", "", 2)); //48
		opInfoCB.Add(new Opcode("bit", "1,c", "", 2)); //49
		opInfoCB.Add(new Opcode("bit", "1,d", "", 2)); //4A
		opInfoCB.Add(new Opcode("bit", "1,e", "", 2)); //4B
		opInfoCB.Add(new Opcode("bit", "1,h", "", 2)); //4C
		opInfoCB.Add(new Opcode("bit", "1,l", "", 2)); //4D
		opInfoCB.Add(new Opcode("bit", "1,(hl)", "", 2)); //4E
		opInfoCB.Add(new Opcode("bit", "1,a", "", 2)); //4F
		opInfoCB.Add(new Opcode("bit", "2,b", "", 2)); //50
		opInfoCB.Add(new Opcode("bit", "2,c", "", 2)); //51
		opInfoCB.Add(new Opcode("bit", "2,d", "", 2)); //52
		opInfoCB.Add(new Opcode("bit", "2,e", "", 2)); //53
		opInfoCB.Add(new Opcode("bit", "2,h", "", 2)); //54
		opInfoCB.Add(new Opcode("bit", "2,l", "", 2)); //55
		opInfoCB.Add(new Opcode("bit", "2,(hl)", "", 2)); //56
		opInfoCB.Add(new Opcode("bit", "2,a", "", 2)); //57
		opInfoCB.Add(new Opcode("bit", "3,b", "", 2)); //58
		opInfoCB.Add(new Opcode("bit", "3,c", "", 2)); //59
		opInfoCB.Add(new Opcode("bit", "3,d", "", 2)); //5A
		opInfoCB.Add(new Opcode("bit", "3,e", "", 2)); //5B
		opInfoCB.Add(new Opcode("bit", "3,h", "", 2)); //5C
		opInfoCB.Add(new Opcode("bit", "3,l", "", 2)); //5D
		opInfoCB.Add(new Opcode("bit", "3,(hl)", "", 2)); //5E
		opInfoCB.Add(new Opcode("bit", "3,a", "", 2)); //5F
		opInfoCB.Add(new Opcode("bit", "4,b", "", 2)); //60
		opInfoCB.Add(new Opcode("bit", "4,c", "", 2)); //61
		opInfoCB.Add(new Opcode("bit", "4,d", "", 2)); //62
		opInfoCB.Add(new Opcode("bit", "4,e", "", 2)); //63
		opInfoCB.Add(new Opcode("bit", "4,h", "", 2)); //64
		opInfoCB.Add(new Opcode("bit", "4,l", "", 2)); //65
		opInfoCB.Add(new Opcode("bit", "4,(hl)", "", 2)); //66
		opInfoCB.Add(new Opcode("bit", "4,a", "", 2)); //67
		opInfoCB.Add(new Opcode("bit", "5,b", "", 2)); //68
		opInfoCB.Add(new Opcode("bit", "5,c", "", 2)); //69
		opInfoCB.Add(new Opcode("bit", "5,d", "", 2)); //6A
		opInfoCB.Add(new Opcode("bit", "5,e", "", 2)); //6B
		opInfoCB.Add(new Opcode("bit", "5,h", "", 2)); //6C
		opInfoCB.Add(new Opcode("bit", "5,l", "", 2)); //6D
		opInfoCB.Add(new Opcode("bit", "5,(hl)", "", 2)); //6E
		opInfoCB.Add(new Opcode("bit", "5,a", "", 2)); //6F
		opInfoCB.Add(new Opcode("bit", "6,b", "", 2)); //70
		opInfoCB.Add(new Opcode("bit", "6,c", "", 2)); //71
		opInfoCB.Add(new Opcode("bit", "6,d", "", 2)); //72
		opInfoCB.Add(new Opcode("bit", "6,e", "", 2)); //73
		opInfoCB.Add(new Opcode("bit", "6,h", "", 2)); //74
		opInfoCB.Add(new Opcode("bit", "6,l", "", 2)); //75
		opInfoCB.Add(new Opcode("bit", "6,(hl)", "", 2)); //76
		opInfoCB.Add(new Opcode("bit", "6,a", "", 2)); //77
		opInfoCB.Add(new Opcode("bit", "7,b", "", 2)); //78
		opInfoCB.Add(new Opcode("bit", "7,c", "", 2)); //79
		opInfoCB.Add(new Opcode("bit", "7,d", "", 2)); //7A
		opInfoCB.Add(new Opcode("bit", "7,e", "", 2)); //7B
		opInfoCB.Add(new Opcode("bit", "7,h", "", 2)); //7C
		opInfoCB.Add(new Opcode("bit", "7,l", "", 2)); //7D
		opInfoCB.Add(new Opcode("bit", "7,(hl)", "", 2)); //7E
		opInfoCB.Add(new Opcode("bit", "7,a", "", 2)); //7F
		opInfoCB.Add(new Opcode("res", "0,b", "", 2)); //80
		opInfoCB.Add(new Opcode("res", "0,c", "", 2)); //81
		opInfoCB.Add(new Opcode("res", "0,d", "", 2)); //82
		opInfoCB.Add(new Opcode("res", "0,e", "", 2)); //83
		opInfoCB.Add(new Opcode("res", "0,h", "", 2)); //84
		opInfoCB.Add(new Opcode("res", "0,l", "", 2)); //85
		opInfoCB.Add(new Opcode("res", "0,(hl)", "", 2)); //86
		opInfoCB.Add(new Opcode("res", "0,a", "", 2)); //87
		opInfoCB.Add(new Opcode("res", "1,b", "", 2)); //88
		opInfoCB.Add(new Opcode("res", "1,c", "", 2)); //89
		opInfoCB.Add(new Opcode("res", "1,d", "", 2)); //8A
		opInfoCB.Add(new Opcode("res", "1,e", "", 2)); //8B
		opInfoCB.Add(new Opcode("res", "1,h", "", 2)); //8C
		opInfoCB.Add(new Opcode("res", "1,l", "", 2)); //8D
		opInfoCB.Add(new Opcode("res", "1,(hl)", "", 2)); //8E
		opInfoCB.Add(new Opcode("res", "1,a", "", 2)); //8F
		opInfoCB.Add(new Opcode("res", "2,b", "", 2)); //90
		opInfoCB.Add(new Opcode("res", "2,c", "", 2)); //91
		opInfoCB.Add(new Opcode("res", "2,d", "", 2)); //92
		opInfoCB.Add(new Opcode("res", "2,e", "", 2)); //93
		opInfoCB.Add(new Opcode("res", "2,h", "", 2)); //94
		opInfoCB.Add(new Opcode("res", "2,l", "", 2)); //95
		opInfoCB.Add(new Opcode("res", "2,(hl)", "", 2)); //96
		opInfoCB.Add(new Opcode("res", "2,a", "", 2)); //97
		opInfoCB.Add(new Opcode("res", "3,b", "", 2)); //98
		opInfoCB.Add(new Opcode("res", "3,c", "", 2)); //99
		opInfoCB.Add(new Opcode("res", "3,d", "", 2)); //9A
		opInfoCB.Add(new Opcode("res", "3,e", "", 2)); //9B
		opInfoCB.Add(new Opcode("res", "3,h", "", 2)); //9C
		opInfoCB.Add(new Opcode("res", "3,l", "", 2)); //9D
		opInfoCB.Add(new Opcode("res", "3,(hl)", "", 2)); //9E
		opInfoCB.Add(new Opcode("res", "3,a", "", 2)); //9F
		opInfoCB.Add(new Opcode("res", "4,b", "", 2)); //A0
		opInfoCB.Add(new Opcode("res", "4,c", "", 2)); //A1
		opInfoCB.Add(new Opcode("res", "4,d", "", 2)); //A2
		opInfoCB.Add(new Opcode("res", "4,e", "", 2)); //A3
		opInfoCB.Add(new Opcode("res", "4,h", "", 2)); //A4
		opInfoCB.Add(new Opcode("res", "4,l", "", 2)); //A5
		opInfoCB.Add(new Opcode("res", "4,(hl)", "", 2)); //A6
		opInfoCB.Add(new Opcode("res", "4,a", "", 2)); //A7
		opInfoCB.Add(new Opcode("res", "5,b", "", 2)); //A8
		opInfoCB.Add(new Opcode("res", "5,c", "", 2)); //A9
		opInfoCB.Add(new Opcode("res", "5,d", "", 2)); //AA
		opInfoCB.Add(new Opcode("res", "5,e", "", 2)); //AB
		opInfoCB.Add(new Opcode("res", "5,h", "", 2)); //AC
		opInfoCB.Add(new Opcode("res", "5,l", "", 2)); //AD
		opInfoCB.Add(new Opcode("res", "5,(hl)", "", 2)); //AE
		opInfoCB.Add(new Opcode("res", "5,a", "", 2)); //AF
		opInfoCB.Add(new Opcode("res", "6,b", "", 2)); //B0
		opInfoCB.Add(new Opcode("res", "6,c", "", 2)); //B1
		opInfoCB.Add(new Opcode("res", "6,d", "", 2)); //B2
		opInfoCB.Add(new Opcode("res", "6,e", "", 2)); //B3
		opInfoCB.Add(new Opcode("res", "6,h", "", 2)); //B4
		opInfoCB.Add(new Opcode("res", "6,l", "", 2)); //B5
		opInfoCB.Add(new Opcode("res", "6,(hl)", "", 2)); //B6
		opInfoCB.Add(new Opcode("res", "6,a", "", 2)); //B7
		opInfoCB.Add(new Opcode("res", "7,b", "", 2)); //B8
		opInfoCB.Add(new Opcode("res", "7,c", "", 2)); //B9
		opInfoCB.Add(new Opcode("res", "7,d", "", 2)); //BA
		opInfoCB.Add(new Opcode("res", "7,e", "", 2)); //BB
		opInfoCB.Add(new Opcode("res", "7,h", "", 2)); //BC
		opInfoCB.Add(new Opcode("res", "7,l", "", 2)); //BD
		opInfoCB.Add(new Opcode("res", "7,(hl)", "", 2)); //BE
		opInfoCB.Add(new Opcode("res", "7,a", "", 2)); //BF
		opInfoCB.Add(new Opcode("set", "0,b", "", 2)); //C0
		opInfoCB.Add(new Opcode("set", "0,c", "", 2)); //C1
		opInfoCB.Add(new Opcode("set", "0,d", "", 2)); //C2
		opInfoCB.Add(new Opcode("set", "0,e", "", 2)); //C3
		opInfoCB.Add(new Opcode("set", "0,h", "", 2)); //C4
		opInfoCB.Add(new Opcode("set", "0,l", "", 2)); //C5
		opInfoCB.Add(new Opcode("set", "0,(hl)", "", 2)); //C6
		opInfoCB.Add(new Opcode("set", "0,a", "", 2)); //C7
		opInfoCB.Add(new Opcode("set", "1,b", "", 2)); //C8
		opInfoCB.Add(new Opcode("set", "1,c", "", 2)); //C9
		opInfoCB.Add(new Opcode("set", "1,d", "", 2)); //CA
		opInfoCB.Add(new Opcode("set", "1,e", "", 2)); //CB
		opInfoCB.Add(new Opcode("set", "1,h", "", 2)); //CC
		opInfoCB.Add(new Opcode("set", "1,l", "", 2)); //CD
		opInfoCB.Add(new Opcode("set", "1,(hl)", "", 2)); //CE
		opInfoCB.Add(new Opcode("set", "1,a", "", 2)); //CF
		opInfoCB.Add(new Opcode("set", "2,b", "", 2)); //D0
		opInfoCB.Add(new Opcode("set", "2,c", "", 2)); //D1
		opInfoCB.Add(new Opcode("set", "2,d", "", 2)); //D2
		opInfoCB.Add(new Opcode("set", "2,e", "", 2)); //D3
		opInfoCB.Add(new Opcode("set", "2,h", "", 2)); //D4
		opInfoCB.Add(new Opcode("set", "2,l", "", 2)); //D5
		opInfoCB.Add(new Opcode("set", "2,(hl)", "", 2)); //D6
		opInfoCB.Add(new Opcode("set", "2,a", "", 2)); //D7
		opInfoCB.Add(new Opcode("set", "3,b", "", 2)); //D8
		opInfoCB.Add(new Opcode("set", "3,c", "", 2)); //D9
		opInfoCB.Add(new Opcode("set", "3,d", "", 2)); //DA
		opInfoCB.Add(new Opcode("set", "3,e", "", 2)); //DB
		opInfoCB.Add(new Opcode("set", "3,h", "", 2)); //DC
		opInfoCB.Add(new Opcode("set", "3,l", "", 2)); //DD
		opInfoCB.Add(new Opcode("set", "3,(hl)", "", 2)); //DE
		opInfoCB.Add(new Opcode("set", "3,a", "", 2)); //DF
		opInfoCB.Add(new Opcode("set", "4,b", "", 2)); //E0
		opInfoCB.Add(new Opcode("set", "4,c", "", 2)); //E1
		opInfoCB.Add(new Opcode("set", "4,d", "", 2)); //E2
		opInfoCB.Add(new Opcode("set", "4,e", "", 2)); //E3
		opInfoCB.Add(new Opcode("set", "4,h", "", 2)); //E4
		opInfoCB.Add(new Opcode("set", "4,l", "", 2)); //E5
		opInfoCB.Add(new Opcode("set", "4,(hl)", "", 2)); //E6
		opInfoCB.Add(new Opcode("set", "4,a", "", 2)); //E7
		opInfoCB.Add(new Opcode("set", "5,b", "", 2)); //E8
		opInfoCB.Add(new Opcode("set", "5,c", "", 2)); //E9
		opInfoCB.Add(new Opcode("set", "5,d", "", 2)); //EA
		opInfoCB.Add(new Opcode("set", "5,e", "", 2)); //EB
		opInfoCB.Add(new Opcode("set", "5,h", "", 2)); //EC
		opInfoCB.Add(new Opcode("set", "5,l", "", 2)); //ED
		opInfoCB.Add(new Opcode("set", "5,(hl)", "", 2)); //EE
		opInfoCB.Add(new Opcode("set", "5,a", "", 2)); //EF
		opInfoCB.Add(new Opcode("set", "6,b", "", 2)); //F0
		opInfoCB.Add(new Opcode("set", "6,c", "", 2)); //F1
		opInfoCB.Add(new Opcode("set", "6,d", "", 2)); //F2
		opInfoCB.Add(new Opcode("set", "6,e", "", 2)); //F3
		opInfoCB.Add(new Opcode("set", "6,h", "", 2)); //F4
		opInfoCB.Add(new Opcode("set", "6,l", "", 2)); //F5
		opInfoCB.Add(new Opcode("set", "6,(hl)", "", 2)); //F6
		opInfoCB.Add(new Opcode("set", "6,a", "", 2)); //F7
		opInfoCB.Add(new Opcode("set", "7,b", "", 2)); //F8
		opInfoCB.Add(new Opcode("set", "7,c", "", 2)); //F9
		opInfoCB.Add(new Opcode("set", "7,d", "", 2)); //FA
		opInfoCB.Add(new Opcode("set", "7,e", "", 2)); //FB
		opInfoCB.Add(new Opcode("set", "7,h", "", 2)); //FC
		opInfoCB.Add(new Opcode("set", "7,l", "", 2)); //FD
		opInfoCB.Add(new Opcode("set", "7,(hl)", "", 2)); //FE
		opInfoCB.Add(new Opcode("set", "7,a", "", 2)); //FF
	}
}

